### ISSUE TITLE
pubgate-philip

### ISSUE THREAD

**Issue by PhilipTrauner** [autogestion/pubgate#22]
Not really an issue, just didn't find another way to contact you: I've noticed that you forked my personal website to use as a basis for an ActivityPub-based blogging engine. 

That's really cool 😁

Just wanted to give you a quick heads up in regards to the less-than-optimal dependency situation: `markdown` as well as `rfeed` are currently personal forks of these projects. With `rfeed` that isn't too much of an issue, as it is basically unmaintained, but `markdown` will start trailing behind upstream at some point.
The codebase currently isn't all that well documented, so if you get stuck on something feel free to reach out 😉 

Oh and by the way: You don't have to name the extension after me 😅 

With kind regards,
Philip Trauner

**Comment by autogestion** [comment]
Hi Philip

I'm considering to utilize only design (fronted part) of your website, and add some js to get/post data from/to pubgate API. So it will be timelines like on mastodon (local, federated), but as tabs, not as columns. And it should be single page app. I don't have a vision how it should be implemented for now)

I decided to not spend efforts on naming, so just used title from original repo. It sounds fine, as for me, anyway  :)
