### ISSUE TITLE
Allowed post formats?

### ISSUE THREAD

**Issue by pwFoo** [autogestion/pubgate#60]
Hi @autogestion,
are formatted (html? which tags?) posts allowed? How to use links, images, headlines and will hashtags replaced by a link?

**Comment by autogestion** [comment]
Html is allowed. Images too, but it's better to use ActivityPub format for images, attach them separately in activitypub post object. This ensure it will work fine in mastodon
As for tags, there is tag and link parsing function, which is used in plugins. And there is javasript parser in pubgate-philip. If posted directly to pubgate API, parsing and replacing will not be applied
