### ISSUE TITLE
Domain based (virtual) users

### ISSUE THREAD

**Issue by pwFoo** [autogestion/pubgate#61]
I like the flexibility of pubgate server backend with api and would like to know if it is still active maintaned?

Would nee features possible?
Multi domain support with virtual users?
One user (login) could dependent on domain name have a (virtual) username dir example used Blog with author Name?

**Comment by autogestion** [comment]
Hi. I switched to Rust, don't think I'll develop it in near feature. Still, you are welcome to fork and continue

**Comment by pwFoo** [comment]
Do you plan to build a rust version of pubgate?

**Comment by autogestion** [comment]
I think if going Rust, It will be better to fork Lemmy or Plume. Pubgate is still minimal federator, while Lemmy and Plume already have many features. Plume is more or less similar to pubgate, it's a blogging platform

My current plan is to apply to blockchain job, I don't think I will have time for this

**Comment by pwFoo** [comment]
I'll test plume. Writefreely is similar to plume, but plume supports Image upload.

Thanks!
