### ISSUE TITLE
Is it a miminmal activitypub backend / server?

### ISSUE THREAD

**Issue by pwFoo** [autogestion/pubgate#9]
Is it a minimal activitypub backend / server for api driven usage?
Are examples available?

Is it possible to add mysql database "driver" to switch db backend?
I'm not experienced with mongo / postgres and prefer mysql ;)

**Comment by autogestion** [comment]
@pwFoo 

- It is going to be minimal activitypub backend server. For now, some required features, like undo, not implemented yet. Estimate to finish is about 2-3 weeks
- As example, you can look at working rss boot https://pubgate.autogestion.org/xatarsis
it is available to interact with bot via mastodon servers, username is xatarsis@pubgate.autogestion.org
- I don't think it is possible to use it with sql databases, for now

**Comment by pwFoo** [comment]
Thanks! I'll what project progress and maybe plan some tests to see how it works 👍 

A feature I miss are (private) group messenging. Would it possible to add that feature to the backend?
Direct messenge with a shortcut for the group (maybe just frontent / ui side...) could be work too.

**Comment by autogestion** [comment]
As far as I know, group messaging is not covered by activitypub specification. If I wrong, please point me to  that part of the spec. There is some custom solution about it from mastodon devs, in progress, if they succeed, and their solution will be approved by other fediverse servers, this feature will be added to pubgate. If not, I'm not sure it is worth to make such feature if it will be supported by only one server

Also, any required feature could be implemented as independent extension to pubgate, like rssbot. I could help with adjusting core server to support such extension

**Comment by pwFoo** [comment]
I think it could be done by direct message to multiple users. So it's a UI thing to show it as (private) group messanging...

So pubgate could be used to handle (create / delete / un-/follow users, post / like / share messages, ...)? 
And handle federation too?

Could be used as server with a ( for example mastodon) client via pubgate api?

**Comment by autogestion** [comment]
@pwFoo 

> So pubgate could be used to handle (create / delete / un-/follow users, post / like / share messages, ...)? And handle federation too?

yes. check here https://documenter.getpostman.com/view/4625755/RzZCFdXv


> Could be used as server with a ( for example mastodon) client via pubgate api?

Mastodon has its own specific (and kind of big) API, which does not meet AP C2S spec. PubGate API meet AP spec, so mastodon clients could not be used with this server. Mastodon-style API could be added as extension to PubGate, but it could be a lot of work.
Also, there was conversation with developers of AndStatus client, they were going to implement compatibility with AP C2S standard, but looks like not yet. If they'll do it, that client could be used with PubGate server.  https://mastodon.social/@autogestion/101075035959098465
